### ISSUE TITLE
Spanish sources 

### ISSUE THREAD

**Issue by Kratos14** [Diegopyl1209/saikouSP#25]
### Summary

Spanish soources like henaojara with spanish dubs 

### The Problem

The sources are already there, they don't have Spanish dubbing

### The Ideal Solution

Henaojara has alot of spanish dubs 

### The Current Solution

To add a new source like henaojara or alike

**Comment by Diegopyl1209** [comment]
https://github.com/Diegopyl1209/saikouSP/releases/tag/LastBeta
lo agregue en la ultima version pero esta como experimental porque la pagina me carga muuuuy lento y no puedo testeralo bien

**Comment by Kratos14** [comment]
Lo estuve probando y esta como tu dices muy lento, cuando encuentra un anime las carátulas no cargan, cuando le doy reproducir video se tarda demasiado y aparece un mensaje de timeout. Intente cambiando las dns y probe las 3 dns pero no funciono.

**Comment by Kratos14** [comment]
Creo que en si son los servidores de henaojara

**Comment by Diegopyl1209** [comment]
> Creo que en si son los servidores de henaojara
si, el probablema son los servidores de henaojara, asi que lo removeré, si tienes otra sugerencias puedes abrir otra issue en github
