### ISSUE TITLE
Nuevo spanish source con doblajes al español latino 

### ISSUE THREAD

**Issue by Kratos14** [Diegopyl1209/saikouSP#27]
### Summary

Source con doblaje al español latino, una pagina que sería buena es animeonline.ninja 

### The Problem

Las páginas que ya están en la App no tienen anime doblado al español latino 

### The Ideal Solution

Agregar un nuevo source animeonline.ninja 

### The Current Solution

Source de animeonline.ninja  o similar

**Comment by Diegopyl1209** [comment]
podría agregar animeonlineninja pero el problema de esta es que las temporadas no están agrupadas en distintos animes como el resto de las paginas sino que están agrupadas dentro de un solo anime, por ejemplo: snk tiene 4 temporadas, en una pagina cualquiera estas 4 temporadas serian divididas como si fueran 4 animes pero animeonlineninja no hace eso, tan solo los agrupa en un mismo anime y divide las temporadas en la sección de episodios

**Comment by Diegopyl1209** [comment]
puedes ver como quedaría usando la extensión de animeonlineninja de aniyomi

**Comment by Kratos14** [comment]
Si, eso que mencionas seria un inconveniente pero por mi no hay problema, si piensas que no está bien podrías agregar otra página que es  animelatinohd. Muchas gracias y perdón por las molestias

**Comment by Diegopyl1209** [comment]
https://github.com/Diegopyl1209/saikouSP/releases/tag/v1.2.0.17.1
