### ISSUE TITLE
Añadir subtitulos en Español Latino en la fuente Kamyroll 

### ISSUE THREAD

**Issue by EsnaiderLR** [Diegopyl1209/saikouSP#29]
### Summary

La fuente Kamyroll carece de los subtitulos en Español Latino

### The Ideal Solution

Añadir codigo de lenguaje latino "es-419" para acceder a subtitulos en Español Latino. 

### Additional Context
 Es raro leer en español españa :p

**Comment by Diegopyl1209** [comment]
Ok, de ahí lo hago

**Comment by EsnaiderLR** [comment]
Muchas gracias Bro,

Si pudieras también agregar alguna fuente de hentai en latino estaría
perfecto.

Saludos.

**Comment by Diegopyl1209** [comment]
> > Ok, de ahí lo hago
> 
> Muchas gracias Bro,
> 
> Si pudieras también agregar alguna fuente de H en latino estaría perfecto.
> 
> Saludos.

Probablemente agregue TioAnime asi que aprovechare de agregar TioHentai
