### ISSUE TITLE
arreglar

### ISSUE THREAD

**Issue by EsnaiderLR** [Diegopyl1209/saikouSP#33]
### Summary

si

### The Problem

la fuente AnimeLatinoHD no funciona 

### The Ideal Solution

arreglar

### Additional Context

por favor

**Comment by Diegopyl1209** [comment]
Ya esta arreglado en este commit 46c6ac72cf5c056e579681d8c2093c3e6ffb707a

**Comment by EsnaiderLR** [comment]
muchas gracias bro!
