### ISSUE TITLE
Algunas cosas interesantes

### ISSUE THREAD

**Issue by CrisCW1990** [Diegopyl1209/saikouSP#35]
### Summary

Tengo alguna idea para la próxima Update

### The Problem

Actualmente la app oficial de Saikou se actualizo, tiene un fix de algo muy importante, pues actualizaron la API de Kamyroll, está permite ver anime en 1080p, en la versión actual de SaikouSP fallan los capítulos de Kamyroll, solo carga la primera temporada de cualquier serie 

SaikouSP no tiene API para manga en español, hay algunas APIs que pueden ser utilices para esto 

### The Ideal Solution

Sería genial una actualización a la versión 1.2.0.23, soy alguien que usa principalmente Kamyroll por la calidad del anime, también sería genial una API para veranime.top está página tiene el catálogo de animes en latino más grande, más de 600 animes en latino, sería genial tener la API.

Hablando ahora del manga, Tachiyomi tiene una API para los mangas de diferentes servidores, entre ellos  LeerCapitulo y LectorManga, si mal no recuerdo tienen la API libre para quien la quiera usar, no estaría mal tener la sesión de mangas funcional en español pero no creo que sea tan necesario teniendo Tachiyomi.

Se que esto fue muy largo, pero quiero agreder tu trabajo, estoy muy feliz de que exista una app así, te admiro mucho, te deseo bendiciones y que todo en tu vida salga como tú quieras, te deseo un feliz día <3

**Comment by Diegopyl1209** [comment]
> la última versión de saikouSP es la 1.2.0.23, solo que por el timing no puse esa versión en el último reléase. Así que todos o la mayoría de los cambios ya están en saikouSP (ya confirme, y si están los últimos cambios de kamyroll)

> La página veranime.top o animeonlineninja, no es posible agregarlas más info aquí: https://github.com/Diegopyl1209/saikouSP/issues/27

> El tema del manga es algo que me han pedido mucho, lo haré pero no será pronto, por el momento estoy ocupando con pruebas y exámenes finales en la universidad, así que cuando termine un poco eso añadiré algún que otra fuente para ver manga, por el momento recomiendo usar tachiyomi o algún fork

**Comment by CrisCW1990** [comment]
Es cierto, el Anime de animeninja solo tiene 1 titulo y dentro de el estan todos los capitulos de todas las temporadas, pero creo que no habria problema, en la ultima version (1.2.0.23) de Saikou oficial (Aclaro oficial porque en la SP no me funciono) cuando pones por ejemplo la tercera temporada de Kimetsu no Yaiba usando kamyroll este te puede mostrar un capitulo de la temporada pasada en algunos casos, pero si pones que el anime es incorrecto (Asi no lo sea) y vuelves  a escoger Kimetsu no yaiba, este te mostrara todos los capitulos de todas las temporadas 
![image](https://user-images.githubusercontent.com/38779980/201454603-5244ea06-4780-4c8b-814d-0b2b8238c8de.png) 
![image](https://user-images.githubusercontent.com/38779980/201454645-35b1a22a-066f-4a72-b4e0-0aada80ed924.png)

En este caso me mostro fue las temporadas pasadas y no la ultima, pero casi siempre me muestra todos los capitulos de todas las temporadas, entonces opino que no habria problema si muestra todos los capitulos del anime, creo que lo importante es poderlo ver en latino.

Y lo del manga creo que no es tan necesario ahora, tenemos Tachiyomi y es muy bueno, aunque seria genial tenerlo en Saikou, para tener todo en una sola aplicacion.

Gracias por tu trabajo <3

**Comment by Diegopyl1209** [comment]
Le echaré un ojo a lo de kamyroll y añadiré la fuente de animeonlineninja en la siguiente update, también es posible que agregue la fuente de Legion anime, hoy saque la extensión en aniyomi así que también podría portearla a saikouSP
