### ISSUE TITLE
No funciona correctamente la Opción de AnimeFLV

### ISSUE THREAD

**Issue by LeinadUchiha** [Diegopyl1209/saikouSP#36]
### Summary

Al eleji Animeflv como opcion para ver animes en vez de se abre Tioanime

### Reproduction Steps

Elegir Animeflv como opción para ver un capítulo

### Expected Result

Esperaba que se abriera el capítulo desde animeflv no desde tioanime

### Actual Result

Paso que al colocar animeflv como opción los animes se abren en tioanime

### Device Information

Versión de saikou 1.2.0.23, xiaomi redmin note 9 y también lo tengo en Windows 11 por WSA

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Pues que por favor arreglen este error, y otra cosa los capítulos de animelatinoHD también cargan en Tioanime, y lo último seria si se podría agregar la henaojara2 que tiene los animes en audio latino y en español de España

**Comment by Diegopyl1209** [comment]
Es intencional, tioanime es un scraper de animeflv

**Comment by LeinadUchiha** [comment]
Si entiendo eso, pero la lista de animes no es la misma, por eso varios animes aunque los busque en la opción de animeflv no son encontrados porque en tioanime no están esos animes. y el de animelatinoHD todos los animes son de tioanime
