### ISSUE TITLE
Android tv problema

### ISSUE THREAD

**Issue by mollejax** [Diegopyl1209/saikouSP#40]
### Summary

Instalo la app en el TV pero solo de queda conjelada en la pantalla de logeo y no hace nada

### Reproduction Steps

Open app

### Expected Result

Fix

### Actual Result

.

### Device Information

.

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Diegopyl1209** [comment]
Existe una version de Saikou para la tv pero nose si tendra algun repositorio en español,, https://github.com/kemuriXD/SaikouTV/releases/tag/v1.1.1

**Comment by mollejax** [comment]
> Existe una version de Saikou para la tv pero nose si tendra algun repositorio en español,, https://github.com/kemuriXD/SaikouTV/releases/tag/v1.1.1

Antes usaba la versión anterior a esta última que subiste y funcionaba en la TV. Esta última actualización tiene ese problema.
